site_name: TTMolE Documentation
site_url: https://jerschro.github.io/ttmole_documentation/
site_author: Jeremy Schroeder
site_description: Documentation for python-based program for editing and creating molecular structures.
repo_name: jerschro/ttmole_documentation
repo_url: https://github.com/jerschro/ttmole_documentation

nav:
  - Home: index.md
  - Introduction : intro.md
  - Installation : installation.md
  - Guides : 
    - guides/index.md
    - Import New : guides/import_new.md
    - Import Append : guides/import_append.md
    - Hydrate Surface : guides/hydrate_surface.md
    - Create Stack : guides/create_stack.md
  - Bugs & Suggestions: bugs_suggestions.md

theme:
  name: material
  features:
    - navigation.instant #for better loading
    - navigation.instant.progress #for better loading
    - navigation.tabs #for tabs of nav folders in header
    # - navigation.sections #groups pages by nav folder #not needed here
    # - navigation.expand #ability for navigation sidebar to expand
    - navigation.indexes #for index pages being clickable in navigation sidebar # must have index.md in folder and not labeled
    - navigation.top #adds scroll to top button when you scroll down
    # - toc.integrate #add toc to navigation panel #says its not compatible with navigation.indexes
    # - content.code.annotate #for code blocks
    # - content.code.copy #for code blocks
    # - navigation.prune #something about optimizing navigation sidebar for 1000 + pages
  
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: lime
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference


plugins:
  - search
  - glightbox: #for images
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true

markdown_extensions:
  - attr_list # for fontawesome
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji # for fontawesome
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # for fontawesome
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:jeremynschroeder@gmail.com
    - icon: fontawesome/solid/t
      link: https://www.depts.ttu.edu/me/combustionlab/
    - icon: fontawesome/brands/github
      link: https://github.com/jerschro

copyright: |
  &copy; 2024 Jeremy Schroeder